openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /api/greeting:
    get:
      tags:
      - greeting-controller
      operationId: greeting
      parameters:
      - name: name
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          default: Worlds
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Greeting'
  /api/post:
    post:
      tags:
      - greeting-controller
      operationId: addGreetings
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Greetingsdlfsjdl'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Greeting'
components:
  schemas:
    Greeting:
      type: object
      properties:
        id:
          type: integer
          format: int64
        content:
          type: string
